modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]]

modId="multiversecraft" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Multiverse Craft" #mandatory


#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

logoFile="examplemod.png" #optional

credits="A Multiverse mod created by William Ministro" #optional

authors="William Ministro" #optional

description='''
This is a mod that is designed to let you visit an alternate universe to your own world.

What will you find in this new, strange world?

'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.multiversecraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
    
[[dependencies.multiversecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
